SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLANG="$SCRIPT_DIR/build/bin/clang"
CLANGXX="$SCRIPT_DIR/build/bin/clang++"
LLVM_CONFIG="$SCRIPT_DIR/build/bin/llvm-config"
SYSROOT="$SCRIPT_DIR/../support/wasi-sysroot"

mkdir -p build-compiler-rt
cd build-compiler-rt
cmake -G Ninja ../compiler-rt \
  -DCMAKE_C_COMPILER="$CLANG" \
  -DCMAKE_CXX_COMPILER="$CLANGXX" \
  -DCMAKE_C_COMPILER_TARGET=wasm32-wasi \
  -DCMAKE_CXX_COMPILER_TARGET=wasm32-wasi \
  -DCMAKE_SYSROOT="$SYSROOT" \
  -DLLVM_CONFIG_PATH="$LLVM_CONFIG" \
  -DCOMPILER_RT_BAREMETAL_BUILD=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
  -DCOMPILER_RT_BUILD_CRT=OFF \
  -DCOMPILER_RT_BUILD_BUILTINS=ON \
  -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
  -DCOMPILER_RT_BUILD_XRAY=OFF \
  -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
  -DCOMPILER_RT_BUILD_PROFILE=OFF
